/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Color;

/**
 *
 * @author EDER H
 */
public class Instrucciones extends javax.swing.JFrame {

    /**
     * Creates new form Instrucciones
     */
    public Instrucciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.GRAY);
        this.cerrarVentanaBoton.setOpaque(false);
        this.cerrarVentanaBoton.setContentAreaFilled(false);
        this.cerrarVentanaBoton.setBorderPainted(false);
        this.avanzarPaginaBoton.setOpaque(false);
        this.avanzarPaginaBoton.setContentAreaFilled(false);
        this.avanzarPaginaBoton.setBorderPainted(false);
        this.voleverPaginaBoton.setOpaque(false);
        this.voleverPaginaBoton.setBorderPainted(false);
        this.voleverPaginaBoton.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarVentanaBoton = new javax.swing.JToggleButton();
        voleverPaginaBoton = new javax.swing.JToggleButton();
        avanzarPaginaBoton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(358, 480));
        setMinimumSize(new java.awt.Dimension(358, 480));
        setPreferredSize(new java.awt.Dimension(358, 480));

        cerrarVentanaBoton.setBackground(new java.awt.Color(204, 204, 204));
        cerrarVentanaBoton.setFont(new java.awt.Font("Papyrus", 3, 14)); // NOI18N
        cerrarVentanaBoton.setForeground(new java.awt.Color(204, 204, 204));
        cerrarVentanaBoton.setText("CERRAR");
        cerrarVentanaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarVentanaBotonActionPerformed(evt);
            }
        });

        voleverPaginaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/left-pointing-arrow.png"))); // NOI18N
        voleverPaginaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voleverPaginaBotonActionPerformed(evt);
            }
        });

        avanzarPaginaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/right-arrow.png"))); // NOI18N
        avanzarPaginaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarPaginaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarVentanaBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(voleverPaginaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(avanzarPaginaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avanzarPaginaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voleverPaginaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrarVentanaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voleverPaginaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voleverPaginaBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voleverPaginaBotonActionPerformed

    private void avanzarPaginaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarPaginaBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avanzarPaginaBotonActionPerformed

    private void cerrarVentanaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarVentanaBotonActionPerformed
        hide();
    }//GEN-LAST:event_cerrarVentanaBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instrucciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton avanzarPaginaBoton;
    private javax.swing.JToggleButton cerrarVentanaBoton;
    private javax.swing.JToggleButton voleverPaginaBoton;
    // End of variables declaration//GEN-END:variables
}
